parameters:
  themountain.emails.contact_email: [jeff.basham@kaff.com,webmaster@939themountain.com]
  themountain.emails.song_request_email: [ eddie.miller@939themountain.com ]
  themountain.emails.freelunch_email: [ webmaster@939themountain.com, kurt.zimmerman@kaff.com ]
  themountain.emails.advertise_email: [jeff.basham@kaff.com, karen.kinney@kaff.com, clay.mccauslin@kaff.com, patrick@magic991.com, webmaster@939themountain.com]
  themountain.emails.contest_email: [kurt.zimmerman@kaff.com, webmaster@939themountain.com]
  themountain.emails.webmaster_email: webmaster@939themountain.com